# Generated by Django 3.1.7 on 2023-03-17 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0076_eligibilityhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='created',
        ),
        migrations.RemoveField(
            model_name='user',
            name='modified',
        ),
    ]
