# Generated by Django 3.1.7 on 2023-03-18 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0077_auto_20230317_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses_rearch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='application.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddressesNew_rearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('address1', models.CharField(default='', max_length=200)),
                ('address2', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(default='', max_length=2)),
                ('zip_code', models.DecimalField(decimal_places=0, max_digits=5)),
                ('is_in_gma', models.BooleanField(default=None, null=True)),
                ('is_city_covered', models.BooleanField(default=None, null=True)),
                ('has_connexion', models.BooleanField(default=None, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name='addressesnew_rearch',
            constraint=models.UniqueConstraint(fields=('address1', 'address2', 'city', 'state', 'zip_code'), name='unq_full_address'),
        ),
        migrations.AddField(
            model_name='addresses_rearch',
            name='eligibility_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='application.addressesnew_rearch'),
        ),
        migrations.AddField(
            model_name='addresses_rearch',
            name='mailing_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='application.addressesnew_rearch'),
        ),
    ]
