# Generated by Django 3.1.7 on 2023-03-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0078_auto_20230317_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMI_rearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('year_valid', models.IntegerField()),
                ('number_persons_in_household', models.CharField(max_length=15)),
                ('ami', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='ami_rearch',
            constraint=models.UniqueConstraint(fields=('number_persons_in_household', 'year_valid'), name='unq_year_values'),
        ),
    ]
