# Generated by Django 3.1.7 on 2023-03-18 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0079_auto_20230317_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eligibility_rearch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='application.user')),
                ('duration_at_address', models.CharField(choices=[('More than 3 Years', 'More than 3 Years'), ('1 to 3 Years', '1 to 3 Years'), ('Less than a Year', 'Less than a Year')], max_length=200)),
                ('number_persons_in_household', models.IntegerField(default=1, verbose_name=100)),
                ('ami_year', models.IntegerField()),
                ('ami_range_min', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ami_range_max', models.DecimalField(decimal_places=2, max_digits=3)),
                ('is_income_verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
