# Generated by Django 3.1.7 on 2023-03-19 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0081_moreinfo_rearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses_rearch',
            name='eligibility_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='application.addressesnew_rearch'),
        ),
        migrations.AlterField(
            model_name='addresses_rearch',
            name='mailing_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='application.addressesnew_rearch'),
        ),
    ]
