# Generated by Django 3.1.7 on 2023-03-19 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0082_auto_20230319_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibilityhistory',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
