# Generated by Django 3.1.7 on 2023-03-19 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0083_auto_20230319_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='iqProgramQualifications_rearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('program_name', models.CharField(max_length=40)),
                ('ami_threshold', models.DecimalField(decimal_places=2, max_digits=3)),
                ('friendly_name', models.CharField(max_length=5000)),
                ('friendly_category', models.CharField(max_length=5000)),
                ('friendly_description', models.CharField(max_length=5000)),
                ('friendly_supplemental_info', models.CharField(max_length=5000)),
                ('learn_more_link', models.CharField(max_length=5000)),
                ('friendly_eligibility_review_period', models.CharField(max_length=5000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='iq_programs_rearch',
            fields=[
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('enrolled_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='application.user')),
                ('is_enrolled', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.iqprogramqualifications_rearch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
