# Generated by Django 3.1.7 on 2023-03-19 17:26

import application.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0084_iq_programs_rearch_iqprogramqualifications_rearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='programs_rearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('program_name', models.CharField(max_length=40)),
                ('ami_threshold', models.DecimalField(decimal_places=2, max_digits=3)),
                ('friendly_program_name', models.CharField(max_length=5000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dashboard_form_rearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('document_path', models.FileField(max_length=5000, upload_to=application.models.userfiles_path)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.programs_rearch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
