# Generated by Django 3.1.7 on 2023-03-19 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0085_dashboard_form_rearch_programs_rearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard_form_rearch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eligibilityhistory',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='eligibility_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
