# Generated by Django 3.1.7 on 2023-03-19 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0086_auto_20230319_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ami_rearch',
            old_name='active',
            new_name='is_active',
        ),
    ]
