# Generated by Django 3.1.7 on 2023-03-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0088_auto_20230319_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iqprogramqualifications_rearch',
            name='program_name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='programs_rearch',
            name='program_name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
