# Generated by Django 3.1.7 on 2023-03-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0089_auto_20230319_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='iqprogramqualifications_rearch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
