# Generated by Django 3.1.7 on 2023-03-20 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0090_iqprogramqualifications_rearch_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='iq_programs_rearch',
        ),
    ]
