# Generated by Django 3.1.7 on 2023-03-20 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0091_delete_iq_programs_rearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='iq_programs_rearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('enrolled_at', models.DateTimeField()),
                ('is_enrolled', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.iqprogramqualifications_rearch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iq_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
