# Generated by Django 3.1.7 on 2023-03-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0092_iq_programs_rearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs_rearch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
