# Generated by Django 3.1.7 on 2023-03-21 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0077_auto_20230321_0813'),
        ('application', '0094_auto_20230321_0719'),
    ]

    operations = [
    ]
